disabled_rules: # rule identifiers to exclude from running
  - comma
  - identifier_name
  - colon
  - cyclomatic_complexity
  - fallthrough
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - opening_brace
  - todo # To enable when we'll release
  - trailing_comma
  - type_body_length
excluded: # paths to ignore during linting
  - .build
